#pragma once
// ICAO airline code → name lookup table
// Sources: flugzeuginfo.net, Wikipedia List of airline codes
// By no means exhaustive, but covers the most common airlines. Feel free to add more!

struct AirlineEntry { char icao[4]; char name[28]; };

static const AirlineEntry kAirlines[] = {
  // ── US Carriers.
  {"UAL", "United Airlines"},
  {"DAL", "Delta Air Lines"},
  {"AAL", "American Airlines"},
  {"SWA", "Southwest Airlines"},
  {"ASA", "Alaska Airlines"},
  {"JBU", "JetBlue Airways"},
  {"NKS", "Spirit Airlines"},
  {"FFT", "Frontier Airlines"},
  {"HAL", "Hawaiian Airlines"},
  {"AAY", "Allegiant Air"},
  {"SKW", "SkyWest Airlines"},
  {"EGF", "American Eagle Airlines"},
  {"ASQ", "Atlantic Southeast"},
  {"LOF", "Trans States Airlines"},
  {"CHQ", "Chautauqua Airlines"},
  {"CPZ", "Compass Airlines"},
  {"COA", "Continental Airlines"},
  {"AWE", "US Airways"},
  {"TRS", "AirTran Airways"},
  {"EJA", "NetJets"},
  {"QXE", "Horizon Air"},
  {"KAI", "Kaiser Air"},
  {"LXJ", "Flexjet"},
  {"EJM", "Jet Speed"},
  {"PVA", "Planet Nine"},
  {"REH", "Reach Medical"},
  {"VJA", "Vista America"},
  {"JSX", "Jetsuite X"},
  {"TWY", "Sunset Aviation"},

  // ── Cargo / freight ──
  {"FDX", "FedEx Express"},
  {"UPS", "UPS Airlines"},
  {"DHL", "DHL Air"},
  {"GTI", "Atlas Air"},
  {"ABW", "AirBridgeCargo"},
  {"CLX", "Cargolux"},
  {"TAY", "TNT Airways"},
  {"ATN", "Air Transport Intl"},
  {"CKS", "Kalitta Air"},
  // ── Canada ──
  {"ACA", "Air Canada"},
  {"JZA", "Air Canada Jazz"},
  {"WJA", "WestJet"},
  {"TSC", "Air Transat"},
  {"CJA", "CanJet"},
  {"POE", "Porter Airlines"},
  // ── Europe ──
  {"DLH", "Lufthansa"},
  {"BAW", "British Airways"},
  {"AFR", "Air France"},
  {"KLM", "KLM Royal Dutch"},
  {"VOI", "Volaris"},
  {"VOS", "Volaris"},
  {"EIN", "Aer Lingus"},
  {"RYR", "Ryanair"},
  {"EZY", "easyJet"},
  {"IBE", "Iberia"},
  {"AZA", "Alitalia"},
  {"AUA", "Austrian Airlines"},
  {"SWR", "Swiss Intl Air Lines"},
  {"BEL", "Brussels Airlines"},
  {"SAS", "SAS Scandinavian"},
  {"ICE", "Icelandair"},
  {"FIN", "Finnair"},
  {"NAX", "Norwegian Air Shuttle"},
  {"EWG", "Eurowings"},
  {"GWI", "Germanwings"},
  {"CFG", "Condor"},
  {"TUI", "TUIfly"},
  {"BLX", "TUIfly Nordic"},
  {"ADR", "Adria Airways"},
  {"CTN", "Croatia Airlines"},
  {"CSA", "Czech Airlines"},
  {"LOT", "LOT Polish Airlines"},
  {"BTI", "airBaltic"},
  {"BRU", "Belavia"},
  {"VLG", "Vueling Airlines"},
  {"IBB", "Binter Canarias"},
  {"ANE", "Air Nostrum"},
  {"CCM", "CCM Airlines"},
  {"BZH", "Brit Air"},
  {"TAP", "TAP Portugal"},
  {"TOM", "Thomson Airways"},
  {"TOM", "Thomson Airways"},
  {"BCY", "CityJet"},
  {"BMR", "BMI Regional"},
  {"BEE", "Flybe"},
  {"LOG", "Loganair"},
  {"AUR", "Aurigny Air Services"},
  {"SDM", "Rossiya Airlines"},
  {"WIF", "Wideroe"},
  // ── Middle East ──
  {"UAE", "Emirates"},
  {"ETD", "Etihad Airways"},
  {"QTR", "Qatar Airways"},
  {"THY", "Turkish Airlines"},
  {"ELY", "El Al Israel Airlines"},
  {"RJA", "Royal Jordanian"},
  {"MEA", "Middle East Airlines"},
  {"SVA", "Saudia"},
  {"KAC", "Kuwait Airways"},
  {"OMA", "Oman Air"},
  {"GUF", "Gulf Air"},
  // ── Asia ──
  {"ANA", "All Nippon Airways"},
  {"JAL", "Japan Airlines"},
  {"CPA", "Cathay Pacific"},
  {"SIA", "Singapore Airlines"},
  {"THA", "Thai Airways Intl"},
  {"AIQ", "Thai AirAsia"},
  {"MAS", "Malaysia Airlines"},
  {"AXM", "AirAsia"},
  {"KAL", "Korean Air"},
  {"AAR", "Asiana Airlines"},
  {"CCA", "Air China"},
  {"CES", "China Eastern"},
  {"CSN", "China Southern"},
  {"HVN", "Vietnam Airlines"},
  {"GIA", "Garuda Indonesia"},
  {"LNI", "Lion Air"},
  {"PAL", "Philippine Airlines"},
  {"EVA", "EVA Air"},
  {"CAL", "China Airlines"},
  {"SLK", "Silk Air"},
  {"SQC", "Singapore Airlines Cargo"},
  {"CXA", "Xiamen Airlines"},
  {"CHH", "Hainan Airlines"},
  {"CSC", "Sichuan Airlines"},
  {"CDG", "Shandong Airlines"},
  {"CAO", "Air China Cargo"},
  {"AIC", "Air India"},
  {"AXB", "Air India Express"},
  {"IGO", "IndiGo"},
  {"JAI", "Jet Airways"},
  {"SEJ", "SpiceJet"},
  {"ALK", "SriLankan Airlines"},
  {"BBC", "Biman Bangladesh"},
  {"DRK", "Druk Air"},
  {"RNA", "Nepal Airlines"},
  {"UBA", "Myanmar Airways Intl"},
  {"HDA", "Dragonair"},
  {"AMU", "Air Macao"},
  {"HKE", "HK Express"},
  {"JST", "Jetstar Airways"},
  {"JSA", "Jetstar Asia"},
  // ── Africa ──
  {"ETH", "Ethiopian Airlines"},
  {"KQA", "Kenya Airways"},
  {"SAA", "South African Airways"},
  {"ARA", "Arik Air"},
  {"DTA", "TAAG Angola Airlines"},
  {"DAH", "Air Algerie"},
  {"RAM", "Royal Air Maroc"},
  {"TAR", "Tunisair"},
  {"MSR", "EgyptAir"},
  {"SYR", "Syrianair"},
  {"IRA", "Iran Air"},
  // ── Latin America ──
  {"ARG", "Aerolineas Argentinas"},
  {"AVA", "Avianca"},
  {"CMP", "Copa Airlines"},
  {"AMX", "AeroMexico"},
  {"TAM", "TAM Airlines"},
  {"AZU", "Azul Brazilian Airlines"},
  {"GLO", "Gol Linhas Aereas"},
  {"LAN", "LAN Airlines"},
  {"AUT", "Austral Lineas Aereas"},
  {"AIJ", "Interjet"},
  {"VIV", "VivaAerobus"},
  // ── Pacific ──
  {"QFA", "Qantas"},
  {"ANZ", "Air New Zealand"},
  {"VOZ", "Virgin Australia"},
  {"FJI", "Fiji Airways"},
  {"AVN", "Air Vanuatu"},
  {"SOL", "Solomon Airlines"},
  {"THT", "Air Tahiti Nui"},
  {"VTA", "Air Tahiti"},
  // ── Russia / CIS ──
  {"AFL", "Aeroflot"},
  {"SBI", "S7 Airlines"},
  {"SVR", "Ural Airlines"},
  {"UTA", "UTair Aviation"},
  {"TSO", "Transaero Airlines"},
  {"UZB", "Uzbekistan Airways"},
  {"TUA", "Turkmenistan Airlines"},
  {"KZR", "Air Astana"},
  {"AZQ", "Silk Way Airlines"},
  {"VDA", "Volga-Dnepr Airlines"},
  // ── Misc 
  {"ABX", "ABX Air"},
  {"AEE", "Aegean Airlines"},
  {"REA", "Aer Arann"},
  {"AFL", "Aeroflot"},
  {"AMF", "Ameriflight"},
  {"AJT", "Amerijet Intl"},
  {"AZN", "Amaszonas"},
  {"APG", "Air People Intl"},
  {"LPV", "Air Alps Aviation"},
  {"REU", "Air Austral"},
  {"BOT", "Air Botswana"},
  {"VBW", "Air Burkina"},
  {"TPC", "Air Caledonie"},
  {"FWI", "Air Caraibes"},
  {"SNC", "Air Cargo Carriers"},
  {"QCL", "Air Class Lineas Aereas"},
  {"CRD", "Air Corridor"},
  {"CRQ", "Air Creebec"},
  {"DLA", "Air Dolomiti"},
  {"AEA", "Air Europa"},
  {"FAJ", "Air Fiji"},
  {"AFN", "Air Freight NZ"},
  {"GGN", "Air Georgian"},
  {"GRL", "Air Greenland"},
  {"AHK", "Air Hong Kong"},
  {"FXI", "Air Iceland"},
  {"LLR", "Air India Regional"},
  {"AIE", "Air Inuit"},
  {"AJM", "Air Jamaica"},
  {"AJX", "Air Japan"},
  {"AKL", "Air Kiribati"},
  {"KOR", "Air Koryo"},
  {"LAL", "Air Labrador"},
  {"AML", "Air Malawi"},
  {"AMC", "Air Malta"},
  {"CWM", "Air Marshall Islands"},
  {"MAU", "Air Mauritius"},
  {"MLD", "Air Moldova"},
  {"NMB", "Air Namibia"},
  {"RLK", "Air Nelson"},
  {"NXA", "Air Next"},
  {"ANK", "Air Nippon"},
  {"ANG", "Air Niugini"},
  {"ANT", "Air North"},
  {"NFA", "Air Norway"},
  {"ADH", "Air One"},
  {"FAJ", "Air Fiji"},
  {"SPM", "Air Saint Pierre"},
  {"SEY", "Air Seychelles"},
  {"ASD", "Air Sinai"},
  {"SVK", "Air Slovakia"},
  {"WOW", "Air Southwest"},
  {"RSI", "Air Sunshine"},
  {"AWI", "Air Wisconsin"},
  {"TCI", "Air Turks and Caicos"},
  {"UGA", "Air Uganda"},
  {"VIM", "Air VIA"},
  {"RVL", "Air Vallee"},
  {"AZW", "Air Zimbabwe"},
  {"XAX", "AirAsia X"},
  {"ACI", "Aircalin"},
  {"ANO", "Airnorth"},
  {"MGB", "Magnicharters"},
  {"VRD", "Virgin America"},
  {"VIR", "Virgin Atlantic"},
  {"BOX", "AeroLogic"},
  {"RCF", "Aeroflot-Cargo"},
  {"SLI", "AeroMexico Connect"},
  {"TAO", "Aeromar"},
  {"RPB", "AeroRepublica"},
  {"WDA", "Wimbi Dira Airways"},
  {"PAS", "Pelita Air Service"},
  {"SJY", "Sriwijaya Air"},
  {"VGN", "Virgin Nigeria"},
  {"EIA", "Evergreen Intl"},
  {"PAC", "Polar Air Cargo"},
  {"ACO", "Arca Colombiana"},
  {"ONA", "Omni Air Intl"},
  {"SOO", "Sun Country Airlines"},
  {"KAP", "CSA Air"},
  {"TRS", "AirTran Airways"},
  {"ATL", "Atlantic Airlines"},
  {"CVC", "Centre-Avia"},
  {"CIR", "Arctic Circle Air"},
  {"TZK", "Tajik Air"},
  {"BWA", "Caribbean Airlines"},
  {"CAY", "Cayman Airways"},
  {"CEB", "Cebu Pacific"},
  {"CUB", "Cubana de Aviacion"},
  {"CYP", "Cyprus Airways"},
  {"IYE", "Yemenia"},
  {"AGB", "Air Gabon"},
  {"CNC", "Congo Airways"},
};

static const int kNumAirlines = sizeof(kAirlines) / sizeof(kAirlines[0]);

// Look up airline name from a callsign (e.g. "UAL8110" → "United Airlines").
// Returns nullptr if not found.
inline const char* lookupAirline(const char* callsign) {
  // Extract leading alpha chars as the ICAO prefix
  char icao[4] = {0, 0, 0, 0};
  int n = 0;
  for (int i = 0; i < 3 && callsign[i] != '\0' && isalpha((unsigned char)callsign[i]); i++)
    icao[n++] = callsign[i];
  if (n == 0) return nullptr;

  for (int i = 0; i < kNumAirlines; i++)
    if (strncmp(kAirlines[i].icao, icao, 4) == 0)
      return kAirlines[i].name;

  return nullptr;
}
